# torch check

In [6]:
import os
import sys
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.optim import lr_scheduler
from torch.autograd import Variable
import numpy as np
import torchvision
from torchvision import datasets, models, transforms
import pdb

In [2]:
# checking 3/4d matrix and 
v = torch.randn(3, 4, 5)
v_ = v.unsqueeze(0)
# v_.shape

l = torch.randn(4, 3, 5, 5)
l.shape[0]
# l[2].shape

var = []
for i in range(l.shape[0]):
    l_ = l[0].unsqueeze(0)
    var.append(l_)
    
la = torch.cat(var)

In [3]:
la.shape

torch.Size([4, 3, 5, 5])

In [4]:
print(la[0])
la[0].view([3*5*5])

tensor([[[-1.0420, -0.0289, -2.1465,  0.9895, -0.0695],
         [ 1.3130,  0.7126,  1.8388, -0.4481, -0.0978],
         [-1.0354, -1.6544, -1.2048, -0.1286,  0.9210],
         [-1.3598,  1.1110, -0.3359,  0.1896, -1.1506],
         [ 0.5437,  0.5690,  0.0077,  0.2840,  0.4576]],

        [[-0.1162,  0.1088,  1.8111, -0.3237, -0.7951],
         [ 0.8977, -0.8446, -0.6297, -0.7065,  0.3885],
         [-0.9309, -0.2669,  0.1507, -1.4785, -1.1385],
         [-0.1821,  1.4161,  0.9808,  0.6285, -0.8624],
         [-0.5708, -0.6469, -0.3995,  1.5150,  0.3257]],

        [[-0.5510, -0.8328,  0.0293, -0.5411,  0.4935],
         [ 1.4119, -0.3021, -2.2915, -0.1624,  0.7817],
         [ 1.4616,  1.5420, -0.1897, -0.1432,  0.3640],
         [-0.5863,  1.3035,  0.7899, -0.4067, -2.3846],
         [ 0.2948,  0.0085, -2.2882,  0.7795, -0.3190]]])


tensor([-1.0420, -0.0289, -2.1465,  0.9895, -0.0695,  1.3130,  0.7126,  1.8388,
        -0.4481, -0.0978, -1.0354, -1.6544, -1.2048, -0.1286,  0.9210, -1.3598,
         1.1110, -0.3359,  0.1896, -1.1506,  0.5437,  0.5690,  0.0077,  0.2840,
         0.4576, -0.1162,  0.1088,  1.8111, -0.3237, -0.7951,  0.8977, -0.8446,
        -0.6297, -0.7065,  0.3885, -0.9309, -0.2669,  0.1507, -1.4785, -1.1385,
        -0.1821,  1.4161,  0.9808,  0.6285, -0.8624, -0.5708, -0.6469, -0.3995,
         1.5150,  0.3257, -0.5510, -0.8328,  0.0293, -0.5411,  0.4935,  1.4119,
        -0.3021, -2.2915, -0.1624,  0.7817,  1.4616,  1.5420, -0.1897, -0.1432,
         0.3640, -0.5863,  1.3035,  0.7899, -0.4067, -2.3846,  0.2948,  0.0085,
        -2.2882,  0.7795, -0.3190])

In [5]:
h, j = torch.unique(l[0], sorted=True, return_inverse=True)

In [6]:
a = torch.tensor([10, 5, 3, 0, 4, 5, 4, 5, 5, 3, 2, 1])
a_ = torch.tensor([[9, 4, 3, 0, 3, 5, 3, 5, 6, 3, 2, 1], [8, 3, 3, 0, 3, 5, 3, 5, 7, 3, 1, 1]], dtype=torch.float32)

In [7]:
unique_labels, unique_id = torch.unique(a, sorted=True, return_inverse=True)

In [8]:
unique_labels

tensor([ 0,  1,  2,  3,  4,  5, 10])

In [9]:
unique_id

tensor([6, 5, 3, 0, 4, 5, 4, 5, 5, 3, 2, 1])

In [10]:
labels, counts = np.unique(unique_id, return_counts=True)

In [11]:
print(labels, counts)
len(counts)

[0 1 2 3 4 5 6] [1 1 1 2 2 4 1]


7

In [5]:
# segmented sum:

index = torch.tensor([[1, 0, 1, 1, 0, 1], [1, 1, 0, 0, 1, 0]])
data = torch.tensor([[5., 1., 7., 2., 3., 4.], [5., 1., 7., 2., 3., 4.]])

torch.zeros(2, 2).scatter_add(1, index, data)

tensor([[ 4., 18.],
        [13.,  9.]])

In [13]:
print(unique_id.shape)
print(a_.shape)
print(len(counts))
print(unique_id.repeat([2,1]))
segmented_sum = torch.zeros(2, len(counts)).scatter_add(1, unique_id.repeat([2,1]), a_)

torch.Size([12])
torch.Size([2, 12])
7
tensor([[6, 5, 3, 0, 4, 5, 4, 5, 5, 3, 2, 1],
        [6, 5, 3, 0, 4, 5, 4, 5, 5, 3, 2, 1]])


In [14]:
a_count = torch.tensor(counts, dtype=torch.float32)
# a_count = a_count.view(-1, 1)
print('seg sum', segmented_sum)
print('counts ', a_count)
mu = torch.div(segmented_sum, a_count)
print('normalized ', mu)

seg sum tensor([[ 0.,  1.,  2.,  6.,  6., 20.,  9.],
        [ 0.,  1.,  1.,  6.,  6., 20.,  8.]])
counts  tensor([1., 1., 1., 2., 2., 4., 1.])
normalized  tensor([[0., 1., 2., 3., 3., 5., 9.],
        [0., 1., 1., 3., 3., 5., 8.]])


In [15]:
print('ids ', unique_id)
print('mu ', mu)
mu_expand = torch.gather(mu, 1, unique_id.repeat([2,1]))
mu_expand

ids  tensor([6, 5, 3, 0, 4, 5, 4, 5, 5, 3, 2, 1])
mu  tensor([[0., 1., 2., 3., 3., 5., 9.],
        [0., 1., 1., 3., 3., 5., 8.]])


tensor([[9., 5., 3., 0., 3., 5., 3., 5., 5., 3., 2., 1.],
        [8., 5., 3., 0., 3., 5., 3., 5., 5., 3., 1., 1.]])

In [16]:
print(mu_expand-a_)
distance = (mu_expand - a_).norm(dim=0)
# distance = torch.norm(mu_expand - a_, 2, -1)
distance

tensor([[ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  0.,  0.,  0.],
        [ 0.,  2.,  0.,  0.,  0.,  0.,  0.,  0., -2.,  0.,  0.,  0.]])


tensor([0.0000, 2.2361, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 2.2361,
        0.0000, 0.0000, 0.0000])

In [17]:
delta_v = 0.03
distance -= torch.tensor(delta_v, dtype=torch.float32)
distance

tensor([-0.0300,  2.2061, -0.0300, -0.0300, -0.0300, -0.0300, -0.0300, -0.0300,
         2.2061, -0.0300, -0.0300, -0.0300])

In [18]:
distance = torch.clamp(distance, min=0.)
distance 

tensor([0.0000, 2.2061, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 2.2061,
        0.0000, 0.0000, 0.0000])

In [19]:
distance = distance.pow(2)
distance

tensor([0.0000, 4.8667, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 4.8667,
        0.0000, 0.0000, 0.0000])

In [20]:
l_var = torch.zeros(len(counts)).scatter_add(0, unique_id, distance)
l_var

tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 9.7335, 0.0000])

In [21]:
l_var = torch.div(l_var, torch.tensor(counts, dtype=torch.float32))
l_var

tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 2.4334, 0.0000])

In [22]:
l_var = l_var.sum()
l_var = torch.div(l_var, len(counts))
l_var

tensor(0.3476)

In [23]:
feature_dim = 2
num_instances = len(counts)
mu_diff = []

# think of a better way to do this:
for i in range(feature_dim):
    for j in range(feature_dim):
        if i != j:
            diff = mu[i] - mu[j]
            mu_diff.append(diff.unsqueeze(0))
            
mu_diff = torch.cat(mu_diff)
mu_diff

tensor([[ 0.,  0.,  1.,  0.,  0.,  0.,  1.],
        [ 0.,  0., -1.,  0.,  0.,  0., -1.]])

In [24]:
mu_norm = mu_diff.norm(dim=1)
mu_norm

tensor([1.4142, 1.4142])

In [25]:
delta_d = 3
mu_norm = (2. * delta_d - mu_norm)
mu_norm

tensor([4.5858, 4.5858])

In [26]:
mu_norm = torch.clamp(mu_norm, min=0.)
mu_norm = mu_norm.pow(2)
mu_norm

tensor([21.0294, 21.0294])

In [27]:
l_dist = mu_norm.mean()
l_dist

tensor(21.0294)

In [28]:
print(mu.norm(dim=1))
print(mu.norm(dim=1).mean())

l_reg = mu.norm(dim=1).mean()
l_reg

tensor([11.3578, 10.4403])
tensor(10.8991)


tensor(10.8991)

In [8]:
a = torch.rand(3, 4, 3)
a

tensor([[[0.2103, 0.6407, 0.3877],
         [0.3804, 0.2378, 0.3120],
         [0.0834, 0.4177, 0.7638],
         [0.0047, 0.0564, 0.7449]],

        [[0.2804, 0.9321, 0.6239],
         [0.4657, 0.4062, 0.2496],
         [0.3264, 0.3163, 0.2057],
         [0.9288, 0.8117, 0.4001]],

        [[0.9084, 0.9216, 0.5634],
         [0.9860, 0.6610, 0.9696],
         [0.7705, 0.9141, 0.8344],
         [0.6839, 0.1700, 0.2007]]])

In [9]:
a[1]

tensor([[0.2804, 0.9321, 0.6239],
        [0.4657, 0.4062, 0.2496],
        [0.3264, 0.3163, 0.2057],
        [0.9288, 0.8117, 0.4001]])